name: CD
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy with Netlify
    runs-on: ubuntu-latest
    steps:
      uses: jsmrcaga/action-netlify-deploy@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        build_directory: "./build"
        NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
        NETLIFY_DEPLOY_TO_PROD: true
