name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # Run npm install and build on our code
      - run: npm install
      - run: npm run build --if-present

      # Deploy the build to Netlify
      - name: Deploy Frontend to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --dir=public --prod
