name: deploy
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.16
      - run: npm install
      - run: npm run lint
      - run: npm run build
  deploy:
    name: Deploy with Netlify
    steps:
      - run: netlify deploy --prod
