name: build
on: [pull_request]
jobs:
  lint_js:
    name: Javascript
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.NETLIFY_SITE_ID }}"
      - run: echo "${{ secrets.NETLIFY_AUTH_TOKEN }}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.4
      - run: npm install
      - run: npm run lint
